//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Member1 = new HashSet<Member>();
            this.Member11 = new HashSet<Member>();
            this.Member12 = new HashSet<Member>();
        }
    
        public int id { get; set; }
        public string Fullname { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Birthplace { get; set; }
        public string Living { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> Father_id { get; set; }
        public Nullable<int> Mother_id { get; set; }
        public Nullable<int> Spouse_id { get; set; }
    
        public virtual ICollection<Member> Member1 { get; set; }
        public virtual Member Member2 { get; set; }
        public virtual ICollection<Member> Member11 { get; set; }
        public virtual Member Member3 { get; set; }
        public virtual ICollection<Member> Member12 { get; set; }
        public virtual Member Member4 { get; set; }
    }
}
